site_name: swatahVision
repo_url: https://github.com/VisionAI4Bharat/swatahVision
repo_name: VisionAI4Bharat/swatahVision

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/fav.ico
  custom_dir: docs/overrides

  font:
    text: Roboto
    code: JetBrains Mono

  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark Mode (default feeling)
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  extra_css:
  - stylesheets/extra.css

  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections

nav:
  # - Home: index.md
  - Getting Started: 
    - Installation: getting_started/install.md

  - Core:
    - Classification: core/classification/core.md
    - Detection: core/detection/core.md

  - Model Zoo: model_zoo/index.md

  - Annotators: 
    - Bounding Box: annotators/box.md
    - Label: annotators/label.md
    - HeatMap: annotators/heatmap.md
    - Trace : annotators/trace.md

  - Trackers:
    - Byte Track: trackers/bytetrack.md

  - Runtime Engine:
      ONNX: runtime/onnx.md
      OpenVino: runtime/openvino.md

  - Examples:
      Count People In Zone: examples/count_people_in_zone.md
      Speed Estimation: examples/speed_estimation.md
      Pose Estimation: examples/pose_estimation.md
      Heatmap Tracking: examples/heatmap_tracking.md
      Time In Zone : examples/time_in_zone.md
      Object Detection : examples/tracking.md
      Traffic Analysis: examples/traffic_analysis.md
      Age Gender: examples/age_gender.md
      Emotion Detection: examples/emotion.md